using System;
using System.Diagnostics.CodeAnalysis;

namespace StandardizedQR
{
    /// <summary>
    /// Currency Codes - ISO 4217
    /// </summary>
    /// <remarks>
    /// The list is current as of June 4, 2018.
    /// </remarks>
    [ExcludeFromCodeCoverage]
    public class Iso4217Currency
    {
        public string Currency { get; set; }
        public string AlphabeticCode { get; set; }
        public int NumericCode { get; set; }

        public static Lazy<Iso4217Currency> Afghanistan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Afghani", AlphabeticCode = "AFN", NumericCode = 971 });
        public static Lazy<Iso4217Currency> AlandIslands => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Albania => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Lek", AlphabeticCode = "ALL", NumericCode = 008 });
        public static Lazy<Iso4217Currency> Algeria => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Algerian Dinar", AlphabeticCode = "DZD", NumericCode = 012 });
        public static Lazy<Iso4217Currency> AmericanSamoa => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> Andorra => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Angola => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Kwanza", AlphabeticCode = "AOA", NumericCode = 973 });
        public static Lazy<Iso4217Currency> Anguilla => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "East Caribbean Dollar", AlphabeticCode = "XCD", NumericCode = 951 });
        public static Lazy<Iso4217Currency> AntiguaAndBarbuda => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "East Caribbean Dollar", AlphabeticCode = "XCD", NumericCode = 951 });
        public static Lazy<Iso4217Currency> Argentina => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Argentine Peso", AlphabeticCode = "ARS", NumericCode = 032 });
        public static Lazy<Iso4217Currency> Armenia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Armenian Dram", AlphabeticCode = "AMD", NumericCode = 051 });
        public static Lazy<Iso4217Currency> Aruba => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Aruban Florin", AlphabeticCode = "AWG", NumericCode = 533 });
        public static Lazy<Iso4217Currency> Australia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Australian Dollar", AlphabeticCode = "AUD", NumericCode = 036 });
        public static Lazy<Iso4217Currency> Austria => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Azerbaijan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Azerbaijan Manat", AlphabeticCode = "AZN", NumericCode = 944 });
        public static Lazy<Iso4217Currency> Bahamas => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Bahamian Dollar", AlphabeticCode = "BSD", NumericCode = 044 });
        public static Lazy<Iso4217Currency> Bahrain => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Bahraini Dinar", AlphabeticCode = "BHD", NumericCode = 048 });
        public static Lazy<Iso4217Currency> Bangladesh => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Taka", AlphabeticCode = "BDT", NumericCode = 050 });
        public static Lazy<Iso4217Currency> Barbados => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Barbados Dollar", AlphabeticCode = "BBD", NumericCode = 052 });
        public static Lazy<Iso4217Currency> Belarus => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Belarusian Ruble", AlphabeticCode = "BYN", NumericCode = 933 });
        public static Lazy<Iso4217Currency> Belgium => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Belize => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Belize Dollar", AlphabeticCode = "BZD", NumericCode = 084 });
        public static Lazy<Iso4217Currency> Benin => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BCEAO", AlphabeticCode = "XOF", NumericCode = 952 });
        public static Lazy<Iso4217Currency> Bermuda => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Bermudian Dollar", AlphabeticCode = "BMD", NumericCode = 060 });
        public static Lazy<Iso4217Currency> BhutanRupee => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Indian Rupee", AlphabeticCode = "INR", NumericCode = 356 });
        public static Lazy<Iso4217Currency> BhutanNgultrum => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Ngultrum", AlphabeticCode = "BTN", NumericCode = 064 });
        public static Lazy<Iso4217Currency> Bolivia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Boliviano", AlphabeticCode = "BOB", NumericCode = 068 });
        public static Lazy<Iso4217Currency> BoliviaMvdol => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Mvdol", AlphabeticCode = "BOV", NumericCode = 984 });
        public static Lazy<Iso4217Currency> Bonaire => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> BosniaAndHerzegovina => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Convertible Mark", AlphabeticCode = "BAM", NumericCode = 977 });
        public static Lazy<Iso4217Currency> Botswana => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Pula", AlphabeticCode = "BWP", NumericCode = 072 });
        public static Lazy<Iso4217Currency> BouvetIsland => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Norwegian Krone", AlphabeticCode = "NOK", NumericCode = 578 });
        public static Lazy<Iso4217Currency> Brazil => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Brazilian Real", AlphabeticCode = "BRL", NumericCode = 986 });
        public static Lazy<Iso4217Currency> BritishIndianOceanTerritory => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> BruneiDarussalam => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Brunei Dollar", AlphabeticCode = "BND", NumericCode = 096 });
        public static Lazy<Iso4217Currency> Bulgaria => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Bulgarian Lev", AlphabeticCode = "BGN", NumericCode = 975 });
        public static Lazy<Iso4217Currency> BurkinaFaso => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BCEAO", AlphabeticCode = "XOF", NumericCode = 952 });
        public static Lazy<Iso4217Currency> Burundi => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Burundi Franc", AlphabeticCode = "BIF", NumericCode = 108 });
        public static Lazy<Iso4217Currency> CaboVerde => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Cabo Verde Escudo", AlphabeticCode = "CVE", NumericCode = 132 });
        public static Lazy<Iso4217Currency> Cambodia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Riel", AlphabeticCode = "KHR", NumericCode = 116 });
        public static Lazy<Iso4217Currency> Cameroon => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BEAC", AlphabeticCode = "XAF", NumericCode = 950 });
        public static Lazy<Iso4217Currency> Canada => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Canadian Dollar", AlphabeticCode = "CAD", NumericCode = 124 });
        public static Lazy<Iso4217Currency> CaymanIslands => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Cayman Islands Dollar", AlphabeticCode = "KYD", NumericCode = 136 });
        public static Lazy<Iso4217Currency> CentralAfricanRepublic => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BEAC", AlphabeticCode = "XAF", NumericCode = 950 });
        public static Lazy<Iso4217Currency> Chad => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BEAC", AlphabeticCode = "XAF", NumericCode = 950 });
        public static Lazy<Iso4217Currency> ChilePeso => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Chilean Peso", AlphabeticCode = "CLP", NumericCode = 152 });
        public static Lazy<Iso4217Currency> ChileFomento => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Unidad de Fomento", AlphabeticCode = "CLF", NumericCode = 990 });
        public static Lazy<Iso4217Currency> China => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Yuan Renminbi", AlphabeticCode = "CNY", NumericCode = 156 });
        public static Lazy<Iso4217Currency> ChristmasIsland => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Australian Dollar", AlphabeticCode = "AUD", NumericCode = 036 });
        public static Lazy<Iso4217Currency> Cocos => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Australian Dollar", AlphabeticCode = "AUD", NumericCode = 036 });
        public static Lazy<Iso4217Currency> ColombiaPeso => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Colombian Peso", AlphabeticCode = "COP", NumericCode = 170 });
        public static Lazy<Iso4217Currency> ColombiaValorReal => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Unidad de Valor Real", AlphabeticCode = "COU", NumericCode = 970 });
        public static Lazy<Iso4217Currency> Comoros => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Comorian Franc ", AlphabeticCode = "KMF", NumericCode = 174 });
        public static Lazy<Iso4217Currency> CongoFranc => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Congolese Franc", AlphabeticCode = "CDF", NumericCode = 976 });
        public static Lazy<Iso4217Currency> CongoBEACH => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BEAC", AlphabeticCode = "XAF", NumericCode = 950 });
        public static Lazy<Iso4217Currency> CookIslands => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "New Zealand Dollar", AlphabeticCode = "NZD", NumericCode = 554 });
        public static Lazy<Iso4217Currency> CostaRica => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Costa Rican Colon", AlphabeticCode = "CRC", NumericCode = 188 });
        public static Lazy<Iso4217Currency> CoteDIvoire => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BCEAO", AlphabeticCode = "XOF", NumericCode = 952 });
        public static Lazy<Iso4217Currency> Croatia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Kuna", AlphabeticCode = "HRK", NumericCode = 191 });
        public static Lazy<Iso4217Currency> CubaPeso => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Cuban Peso", AlphabeticCode = "CUP", NumericCode = 192 });
        public static Lazy<Iso4217Currency> CubaPesoConvertible => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Peso Convertible", AlphabeticCode = "CUC", NumericCode = 931 });
        public static Lazy<Iso4217Currency> Curaçao => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Netherlands Antillean Guilder", AlphabeticCode = "ANG", NumericCode = 532 });
        public static Lazy<Iso4217Currency> Cyprus => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Czechia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Czech Koruna", AlphabeticCode = "CZK", NumericCode = 203 });
        public static Lazy<Iso4217Currency> Denmark => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Danish Krone", AlphabeticCode = "DKK", NumericCode = 208 });
        public static Lazy<Iso4217Currency> Djibouti => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Djibouti Franc", AlphabeticCode = "DJF", NumericCode = 262 });
        public static Lazy<Iso4217Currency> Dominica => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "East Caribbean Dollar", AlphabeticCode = "XCD", NumericCode = 951 });
        public static Lazy<Iso4217Currency> DominicanRepublic => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Dominican Peso", AlphabeticCode = "DOP", NumericCode = 214 });
        public static Lazy<Iso4217Currency> Ecuador => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> Egypt => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Egyptian Pound", AlphabeticCode = "EGP", NumericCode = 818 });
        public static Lazy<Iso4217Currency> ElSalvadorColon => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "El Salvador Colon", AlphabeticCode = "SVC", NumericCode = 222 });
        public static Lazy<Iso4217Currency> ElSalvadorUSD => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> EquatorialGuinea => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BEAC", AlphabeticCode = "XAF", NumericCode = 950 });
        public static Lazy<Iso4217Currency> Eritrea => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Nakfa", AlphabeticCode = "ERN", NumericCode = 232 });
        public static Lazy<Iso4217Currency> Estonia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Ethiopia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Ethiopian Birr", AlphabeticCode = "ETB", NumericCode = 230 });
        public static Lazy<Iso4217Currency> EuropeanUnion => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> FalklandIslands => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Falkland Islands Pound", AlphabeticCode = "FKP", NumericCode = 238 });
        public static Lazy<Iso4217Currency> FaroeIslands => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Danish Krone", AlphabeticCode = "DKK", NumericCode = 208 });
        public static Lazy<Iso4217Currency> Fiji => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Fiji Dollar", AlphabeticCode = "FJD", NumericCode = 242 });
        public static Lazy<Iso4217Currency> Finland => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> France => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> FrenchGuiana => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> FrenchPolynesia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFP Franc", AlphabeticCode = "XPF", NumericCode = 953 });
        public static Lazy<Iso4217Currency> FrenchSouthernTerritories => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Gabon => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BEAC", AlphabeticCode = "XAF", NumericCode = 950 });
        public static Lazy<Iso4217Currency> Gambia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Dalasi", AlphabeticCode = "GMD", NumericCode = 270 });
        public static Lazy<Iso4217Currency> Georgia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Lari", AlphabeticCode = "GEL", NumericCode = 981 });
        public static Lazy<Iso4217Currency> Germany => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Ghana => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Ghana Cedi", AlphabeticCode = "GHS", NumericCode = 936 });
        public static Lazy<Iso4217Currency> Gibraltar => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Gibraltar Pound", AlphabeticCode = "GIP", NumericCode = 292 });
        public static Lazy<Iso4217Currency> Greece => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Greenland => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Danish Krone", AlphabeticCode = "DKK", NumericCode = 208 });
        public static Lazy<Iso4217Currency> Grenada => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "East Caribbean Dollar", AlphabeticCode = "XCD", NumericCode = 951 });
        public static Lazy<Iso4217Currency> Guadeloupe => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Guam => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> Guatemala => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Quetzal", AlphabeticCode = "GTQ", NumericCode = 320 });
        public static Lazy<Iso4217Currency> Guernsey => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Pound Sterling", AlphabeticCode = "GBP", NumericCode = 826 });
        public static Lazy<Iso4217Currency> Guinea => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Guinean Franc", AlphabeticCode = "GNF", NumericCode = 324 });
        public static Lazy<Iso4217Currency> GuineaBissau => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BCEAO", AlphabeticCode = "XOF", NumericCode = 952 });
        public static Lazy<Iso4217Currency> Guyana => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Guyana Dollar", AlphabeticCode = "GYD", NumericCode = 328 });
        public static Lazy<Iso4217Currency> HaitiGourde => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Gourde", AlphabeticCode = "HTG", NumericCode = 332 });
        public static Lazy<Iso4217Currency> HaitiUSD => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> HeardIslandAndMcdonaldIslands => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Australian Dollar", AlphabeticCode = "AUD", NumericCode = 036 });
        public static Lazy<Iso4217Currency> HolySee => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Honduras => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Lempira", AlphabeticCode = "HNL", NumericCode = 340 });
        public static Lazy<Iso4217Currency> HongKong => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Hong Kong Dollar", AlphabeticCode = "HKD", NumericCode = 344 });
        public static Lazy<Iso4217Currency> Hungary => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Forint", AlphabeticCode = "HUF", NumericCode = 348 });
        public static Lazy<Iso4217Currency> Iceland => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Iceland Krona", AlphabeticCode = "ISK", NumericCode = 352 });
        public static Lazy<Iso4217Currency> India => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Indian Rupee", AlphabeticCode = "INR", NumericCode = 356 });
        public static Lazy<Iso4217Currency> Indonesia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Rupiah", AlphabeticCode = "IDR", NumericCode = 360 });
        public static Lazy<Iso4217Currency> InternationalMonetaryFund => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "SDR (Special Drawing Right)", AlphabeticCode = "XDR", NumericCode = 960 });
        public static Lazy<Iso4217Currency> Iran => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Iranian Rial", AlphabeticCode = "IRR", NumericCode = 364 });
        public static Lazy<Iso4217Currency> Iraq => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Iraqi Dinar", AlphabeticCode = "IQD", NumericCode = 368 });
        public static Lazy<Iso4217Currency> Ireland => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> IsleOfMan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Pound Sterling", AlphabeticCode = "GBP", NumericCode = 826 });
        public static Lazy<Iso4217Currency> Israel => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "New Israeli Sheqel", AlphabeticCode = "ILS", NumericCode = 376 });
        public static Lazy<Iso4217Currency> Italy => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Jamaica => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Jamaican Dollar", AlphabeticCode = "JMD", NumericCode = 388 });
        public static Lazy<Iso4217Currency> Japan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Yen", AlphabeticCode = "JPY", NumericCode = 392 });
        public static Lazy<Iso4217Currency> Jersey => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Pound Sterling", AlphabeticCode = "GBP", NumericCode = 826 });
        public static Lazy<Iso4217Currency> Jordan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Jordanian Dinar", AlphabeticCode = "JOD", NumericCode = 400 });
        public static Lazy<Iso4217Currency> Kazakhstan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Tenge", AlphabeticCode = "KZT", NumericCode = 398 });
        public static Lazy<Iso4217Currency> Kenya => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Kenyan Shilling", AlphabeticCode = "KES", NumericCode = 404 });
        public static Lazy<Iso4217Currency> Kiribati => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Australian Dollar", AlphabeticCode = "AUD", NumericCode = 036 });
        public static Lazy<Iso4217Currency> KoreaDemocraticPeopleRepublicOf => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "North Korean Won", AlphabeticCode = "KPW", NumericCode = 408 });
        public static Lazy<Iso4217Currency> KoreaTheRepublicOf => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Won", AlphabeticCode = "KRW", NumericCode = 410 });
        public static Lazy<Iso4217Currency> Kuwait => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Kuwaiti Dinar", AlphabeticCode = "KWD", NumericCode = 414 });
        public static Lazy<Iso4217Currency> Kyrgyzstan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Som", AlphabeticCode = "KGS", NumericCode = 417 });
        public static Lazy<Iso4217Currency> Lao => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Lao Kip", AlphabeticCode = "LAK", NumericCode = 418 });
        public static Lazy<Iso4217Currency> Latvia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Lebanon => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Lebanese Pound", AlphabeticCode = "LBP", NumericCode = 422 });
        public static Lazy<Iso4217Currency> LesothoLoti => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Loti", AlphabeticCode = "LSL", NumericCode = 426 });
        public static Lazy<Iso4217Currency> LesothoRand => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Rand", AlphabeticCode = "ZAR", NumericCode = 710 });
        public static Lazy<Iso4217Currency> Liberia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Liberian Dollar", AlphabeticCode = "LRD", NumericCode = 430 });
        public static Lazy<Iso4217Currency> Libya => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Libyan Dinar", AlphabeticCode = "LYD", NumericCode = 434 });
        public static Lazy<Iso4217Currency> Liechtenstein => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Swiss Franc", AlphabeticCode = "CHF", NumericCode = 756 });
        public static Lazy<Iso4217Currency> Lithuania => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Luxembourg => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Macao => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Pataca", AlphabeticCode = "MOP", NumericCode = 446 });
        public static Lazy<Iso4217Currency> Macedonia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Denar", AlphabeticCode = "MKD", NumericCode = 807 });
        public static Lazy<Iso4217Currency> Madagascar => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Malagasy Ariary", AlphabeticCode = "MGA", NumericCode = 969 });
        public static Lazy<Iso4217Currency> Malawi => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Malawi Kwacha", AlphabeticCode = "MWK", NumericCode = 454 });
        public static Lazy<Iso4217Currency> Malaysia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Malaysian Ringgit", AlphabeticCode = "MYR", NumericCode = 458 });
        public static Lazy<Iso4217Currency> Maldives => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Rufiyaa", AlphabeticCode = "MVR", NumericCode = 462 });
        public static Lazy<Iso4217Currency> Mali => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BCEAO", AlphabeticCode = "XOF", NumericCode = 952 });
        public static Lazy<Iso4217Currency> Malta => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> MarshallIslands => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> Martinique => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Mauritania => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Ouguiya", AlphabeticCode = "MRU", NumericCode = 929 });
        public static Lazy<Iso4217Currency> Mauritius => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Mauritius Rupee", AlphabeticCode = "MUR", NumericCode = 480 });
        public static Lazy<Iso4217Currency> Mayotte => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> MemberCountriesOfTheAfricanDevelopmentBankGroup => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "ADB Unit of Account", AlphabeticCode = "XUA", NumericCode = 965 });
        public static Lazy<Iso4217Currency> MexicoPeso => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Mexican Peso", AlphabeticCode = "MXN", NumericCode = 484 });
        public static Lazy<Iso4217Currency> MexicoUDI => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Mexican Unidad de Inversion (UDI)", AlphabeticCode = "MXV", NumericCode = 979 });
        public static Lazy<Iso4217Currency> Micronesia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> Moldova => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Moldovan Leu", AlphabeticCode = "MDL", NumericCode = 498 });
        public static Lazy<Iso4217Currency> Monaco => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Mongolia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Tugrik", AlphabeticCode = "MNT", NumericCode = 496 });
        public static Lazy<Iso4217Currency> Montenegro => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Montserrat => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "East Caribbean Dollar", AlphabeticCode = "XCD", NumericCode = 951 });
        public static Lazy<Iso4217Currency> Morocco => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Moroccan Dirham", AlphabeticCode = "MAD", NumericCode = 504 });
        public static Lazy<Iso4217Currency> Mozambique => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Mozambique Metical", AlphabeticCode = "MZN", NumericCode = 943 });
        public static Lazy<Iso4217Currency> Myanmar => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Kyat", AlphabeticCode = "MMK", NumericCode = 104 });
        public static Lazy<Iso4217Currency> NamibiaDollar => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Namibia Dollar", AlphabeticCode = "NAD", NumericCode = 516 });
        public static Lazy<Iso4217Currency> NamibiaRand => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Rand", AlphabeticCode = "ZAR", NumericCode = 710 });
        public static Lazy<Iso4217Currency> Nauru => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Australian Dollar", AlphabeticCode = "AUD", NumericCode = 036 });
        public static Lazy<Iso4217Currency> Nepal => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Nepalese Rupee", AlphabeticCode = "NPR", NumericCode = 524 });
        public static Lazy<Iso4217Currency> Netherlands => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> NewCaledonia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFP Franc", AlphabeticCode = "XPF", NumericCode = 953 });
        public static Lazy<Iso4217Currency> NewZealand => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "New Zealand Dollar", AlphabeticCode = "NZD", NumericCode = 554 });
        public static Lazy<Iso4217Currency> Nicaragua => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Cordoba Oro", AlphabeticCode = "NIO", NumericCode = 558 });
        public static Lazy<Iso4217Currency> Niger => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BCEAO", AlphabeticCode = "XOF", NumericCode = 952 });
        public static Lazy<Iso4217Currency> Nigeria => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Naira", AlphabeticCode = "NGN", NumericCode = 566 });
        public static Lazy<Iso4217Currency> Niue => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "New Zealand Dollar", AlphabeticCode = "NZD", NumericCode = 554 });
        public static Lazy<Iso4217Currency> NorfolkIsland => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Australian Dollar", AlphabeticCode = "AUD", NumericCode = 036 });
        public static Lazy<Iso4217Currency> NorthernMarianaIslands => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> Norway => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Norwegian Krone", AlphabeticCode = "NOK", NumericCode = 578 });
        public static Lazy<Iso4217Currency> Oman => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Rial Omani", AlphabeticCode = "OMR", NumericCode = 512 });
        public static Lazy<Iso4217Currency> Pakistan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Pakistan Rupee", AlphabeticCode = "PKR", NumericCode = 586 });
        public static Lazy<Iso4217Currency> Palau => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> PanamaBalboa => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Balboa", AlphabeticCode = "PAB", NumericCode = 590 });
        public static Lazy<Iso4217Currency> PanamaUSD => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> PapuaNewGuinea => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Kina", AlphabeticCode = "PGK", NumericCode = 598 });
        public static Lazy<Iso4217Currency> Paraguay => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Guarani", AlphabeticCode = "PYG", NumericCode = 600 });
        public static Lazy<Iso4217Currency> Peru => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Sol", AlphabeticCode = "PEN", NumericCode = 604 });
        public static Lazy<Iso4217Currency> Philippines => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Philippine Piso", AlphabeticCode = "PHP", NumericCode = 608 });
        public static Lazy<Iso4217Currency> Pitcairn => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "New Zealand Dollar", AlphabeticCode = "NZD", NumericCode = 554 });
        public static Lazy<Iso4217Currency> Poland => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Zloty", AlphabeticCode = "PLN", NumericCode = 985 });
        public static Lazy<Iso4217Currency> Portugal => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> PuertoRico => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> Qatar => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Qatari Rial", AlphabeticCode = "QAR", NumericCode = 634 });
        public static Lazy<Iso4217Currency> Reunion => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Romania => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Romanian Leu", AlphabeticCode = "RON", NumericCode = 946 });
        public static Lazy<Iso4217Currency> RussianFederation => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Russian Ruble", AlphabeticCode = "RUB", NumericCode = 643 });
        public static Lazy<Iso4217Currency> Rwanda => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Rwanda Franc", AlphabeticCode = "RWF", NumericCode = 646 });
        public static Lazy<Iso4217Currency> SaintBarthélemy => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> SaintHelena => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Saint Helena Pound", AlphabeticCode = "SHP", NumericCode = 654 });
        public static Lazy<Iso4217Currency> SaintKitts => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "East Caribbean Dollar", AlphabeticCode = "XCD", NumericCode = 951 });
        public static Lazy<Iso4217Currency> SaintLucia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "East Caribbean Dollar", AlphabeticCode = "XCD", NumericCode = 951 });
        public static Lazy<Iso4217Currency> SaintMartinFrenchPart => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> SaintPierreAndMiquelon => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> SaintVincentAndTheGrenadines => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "East Caribbean Dollar", AlphabeticCode = "XCD", NumericCode = 951 });
        public static Lazy<Iso4217Currency> Samoa => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Tala", AlphabeticCode = "WST", NumericCode = 882 });
        public static Lazy<Iso4217Currency> SanMarino => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> SaoTomeAndPrincipe => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Dobra", AlphabeticCode = "STN", NumericCode = 930 });
        public static Lazy<Iso4217Currency> SaudiArabia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Saudi Riyal", AlphabeticCode = "SAR", NumericCode = 682 });
        public static Lazy<Iso4217Currency> Senegal => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BCEAO", AlphabeticCode = "XOF", NumericCode = 952 });
        public static Lazy<Iso4217Currency> Serbia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Serbian Dinar", AlphabeticCode = "RSD", NumericCode = 941 });
        public static Lazy<Iso4217Currency> Seychelles => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Seychelles Rupee", AlphabeticCode = "SCR", NumericCode = 690 });
        public static Lazy<Iso4217Currency> SierraLeone => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Leone", AlphabeticCode = "SLL", NumericCode = 694 });
        public static Lazy<Iso4217Currency> Singapore => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Singapore Dollar", AlphabeticCode = "SGD", NumericCode = 702 });
        public static Lazy<Iso4217Currency> SintMaartenDutchPart => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Netherlands Antillean Guilder", AlphabeticCode = "ANG", NumericCode = 532 });
        public static Lazy<Iso4217Currency> SistemaUnitarioDeCompensacionRegionalDePagosSucre => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Sucre", AlphabeticCode = "XSU", NumericCode = 994 });
        public static Lazy<Iso4217Currency> Slovakia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> Slovenia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> SolomonIslands => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Solomon Islands Dollar", AlphabeticCode = "SBD", NumericCode = 090 });
        public static Lazy<Iso4217Currency> Somalia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Somali Shilling", AlphabeticCode = "SOS", NumericCode = 706 });
        public static Lazy<Iso4217Currency> SouthAfrica => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Rand", AlphabeticCode = "ZAR", NumericCode = 710 });
        public static Lazy<Iso4217Currency> SouthSudan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "South Sudanese Pound", AlphabeticCode = "SSP", NumericCode = 728 });
        public static Lazy<Iso4217Currency> Spain => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Euro", AlphabeticCode = "EUR", NumericCode = 978 });
        public static Lazy<Iso4217Currency> SriLanka => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Sri Lanka Rupee", AlphabeticCode = "LKR", NumericCode = 144 });
        public static Lazy<Iso4217Currency> Sudan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Sudanese Pound", AlphabeticCode = "SDG", NumericCode = 938 });
        public static Lazy<Iso4217Currency> Suriname => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Surinam Dollar", AlphabeticCode = "SRD", NumericCode = 968 });
        public static Lazy<Iso4217Currency> SvalbardAndJanMayen => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Norwegian Krone", AlphabeticCode = "NOK", NumericCode = 578 });
        public static Lazy<Iso4217Currency> Swaziland => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Lilangeni", AlphabeticCode = "SZL", NumericCode = 748 });
        public static Lazy<Iso4217Currency> Sweden => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Swedish Krona", AlphabeticCode = "SEK", NumericCode = 752 });
        public static Lazy<Iso4217Currency> SwitzerlandFranc => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Swiss Franc", AlphabeticCode = "CHF", NumericCode = 756 });
        public static Lazy<Iso4217Currency> SwitzerlandWirEuro => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "WIR Euro", AlphabeticCode = "CHE", NumericCode = 947 });
        public static Lazy<Iso4217Currency> SwitzerlandWirFranc => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "WIR Franc", AlphabeticCode = "CHW", NumericCode = 948 });
        public static Lazy<Iso4217Currency> SyrianArabRepublic => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Syrian Pound", AlphabeticCode = "SYP", NumericCode = 760 });
        public static Lazy<Iso4217Currency> Taiwan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "New Taiwan Dollar", AlphabeticCode = "TWD", NumericCode = 901 });
        public static Lazy<Iso4217Currency> Tajikistan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Somoni", AlphabeticCode = "TJS", NumericCode = 972 });
        public static Lazy<Iso4217Currency> Tanzania => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Tanzanian Shilling", AlphabeticCode = "TZS", NumericCode = 834 });
        public static Lazy<Iso4217Currency> Thailand => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Baht", AlphabeticCode = "THB", NumericCode = 764 });
        public static Lazy<Iso4217Currency> TimorLeste => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> Togo => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFA Franc BCEAO", AlphabeticCode = "XOF", NumericCode = 952 });
        public static Lazy<Iso4217Currency> Tokelau => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "New Zealand Dollar", AlphabeticCode = "NZD", NumericCode = 554 });
        public static Lazy<Iso4217Currency> Tonga => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Pa’anga", AlphabeticCode = "TOP", NumericCode = 776 });
        public static Lazy<Iso4217Currency> TrinidadAndTobago => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Trinidad and Tobago Dollar", AlphabeticCode = "TTD", NumericCode = 780 });
        public static Lazy<Iso4217Currency> Tunisia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Tunisian Dinar", AlphabeticCode = "TND", NumericCode = 788 });
        public static Lazy<Iso4217Currency> Turkey => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Turkish Lira", AlphabeticCode = "TRY", NumericCode = 949 });
        public static Lazy<Iso4217Currency> Turkmenistan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Turkmenistan New Manat", AlphabeticCode = "TMT", NumericCode = 934 });
        public static Lazy<Iso4217Currency> TurksAndCaicosIslands => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> Tuvalu => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Australian Dollar", AlphabeticCode = "AUD", NumericCode = 036 });
        public static Lazy<Iso4217Currency> Uganda => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Uganda Shilling", AlphabeticCode = "UGX", NumericCode = 800 });
        public static Lazy<Iso4217Currency> Ukraine => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Hryvnia", AlphabeticCode = "UAH", NumericCode = 980 });
        public static Lazy<Iso4217Currency> UnitedArabEmirates => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "UAE Dirham", AlphabeticCode = "AED", NumericCode = 784 });
        public static Lazy<Iso4217Currency> UnitedKingdomOfGreatBritainAndNorthernIreland => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Pound Sterling", AlphabeticCode = "GBP", NumericCode = 826 });
        public static Lazy<Iso4217Currency> UnitedStatesMinorOutlyingIslands => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> UnitedStatesUSD => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> UnitedStatesUSDNextDay => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar (Next day)", AlphabeticCode = "USN", NumericCode = 997 });
        public static Lazy<Iso4217Currency> UruguayPeso => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Peso Uruguayo", AlphabeticCode = "UYU", NumericCode = 858 });
        public static Lazy<Iso4217Currency> UruguayUI => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Uruguay Peso en Unidades Indexadas (UI)", AlphabeticCode = "UYI", NumericCode = 940 });
        public static Lazy<Iso4217Currency> Uzbekistan => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Uzbekistan Sum", AlphabeticCode = "UZS", NumericCode = 860 });
        public static Lazy<Iso4217Currency> Vanuatu => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Vatu", AlphabeticCode = "VUV", NumericCode = 548 });
        public static Lazy<Iso4217Currency> Venezuela => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Bolívar", AlphabeticCode = "VEF", NumericCode = 937 });
        public static Lazy<Iso4217Currency> Vietnam => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Dong", AlphabeticCode = "VND", NumericCode = 704 });
        public static Lazy<Iso4217Currency> VirginIslandsBritish => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> VirginIslandsUS => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "US Dollar", AlphabeticCode = "USD", NumericCode = 840 });
        public static Lazy<Iso4217Currency> WallisAndFutuna => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "CFP Franc", AlphabeticCode = "XPF", NumericCode = 953 });
        public static Lazy<Iso4217Currency> WesternSahara => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Moroccan Dirham", AlphabeticCode = "MAD", NumericCode = 504 });
        public static Lazy<Iso4217Currency> Yemen => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Yemeni Rial", AlphabeticCode = "YER", NumericCode = 886 });
        public static Lazy<Iso4217Currency> Zambia => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Zambian Kwacha", AlphabeticCode = "ZMW", NumericCode = 967 });
        public static Lazy<Iso4217Currency> Zimbabwe => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Zimbabwe Dollar", AlphabeticCode = "ZWL", NumericCode = 932 });
        public static Lazy<Iso4217Currency> Zz01_BondMarketsUnitEuropean_eurco => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Bond Markets Unit European Composite Unit (EURCO)", AlphabeticCode = "XBA", NumericCode = 955 });
        public static Lazy<Iso4217Currency> Zz02_BondMarketsUnitEuropean_emu6 => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Bond Markets Unit European Monetary Unit (E.M.U.-6)", AlphabeticCode = "XBB", NumericCode = 956 });
        public static Lazy<Iso4217Currency> Zz03_BondMarketsUnitEuropean_eua9 => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", AlphabeticCode = "XBC", NumericCode = 957 });
        public static Lazy<Iso4217Currency> Zz04_BondMarketsUnitEuropean_eua17 => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", AlphabeticCode = "XBD", NumericCode = 958 });
        public static Lazy<Iso4217Currency> Zz06_Testing_code => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Codes specifically reserved for testing purposes", AlphabeticCode = "XTS", NumericCode = 963 });
        public static Lazy<Iso4217Currency> Zz07_No_currency => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "The codes assigned for transactions where no currency is involved", AlphabeticCode = "XXX", NumericCode = 999 });
        public static Lazy<Iso4217Currency> Zz08_Gold => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Gold", AlphabeticCode = "XAU", NumericCode = 959 });
        public static Lazy<Iso4217Currency> Zz09_Palladium => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Palladium", AlphabeticCode = "XPD", NumericCode = 964 });
        public static Lazy<Iso4217Currency> Zz10_Platinum => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Platinum", AlphabeticCode = "XPT", NumericCode = 962 });
        public static Lazy<Iso4217Currency> Zz11_Silver => new Lazy<Iso4217Currency>(() => new Iso4217Currency { Currency = "Silver", AlphabeticCode = "XAG", NumericCode = 961 });
    }
}
